### ISSUE TITLE
Dark Color Style / Dark theme?

### ISSUE THREAD

**Issue by fastrizwaan** [mignaway/EpubReader#17]
We have only white and sepia colors for the text, could we have dark theme, like dark themed apps?

![image](https://github.com/mignaway/EpubReader/assets/1161682/e4fb9627-21fd-4e9c-8330-02138d7f9cef)

**Comment by mignaway** [comment]
Yes sure, today I'll see if I can work on it and add the dark mode. It would be handy to have an auto-updater (which maybe I will do in the short term)

**Comment by mignaway** [comment]
Since the app is a mess in terms of scalability and it would be too difficult to do a lot of things, I'm thinking of recreating the app as it is using react as frontend framework, so I can fix it up and have an app that can evolve. This will probably take me some time tho

**Comment by franzmaliszt** [comment]
Thanks for the work, this has been my primary reader for over a year, and a proper dark mode would be most appreciated. 
I attempted to contribute in the past but jquery felt enigmatic to me and i gave up since I'm not really a JS guy myself. I reckon i would have better time with React. I'm excited to see what this is going to evolve to.

**Comment by ronilaukkarinen** [comment]
+1.

I love this reader. Dark mode would be amazing.

**Comment by mignaway** [comment]
#22
