### ISSUE TITLE
Migration to Tauri?

### ISSUE THREAD

**Issue by brigazvi** [mignaway/EpubReader#19]
first of all: this app looks cool as hell.
I started looking for a good epub reader because Calibre is too ugly to bear. then I ran into someone on Reddit who recommended it.
I love the design.
@mignaway I would love to hear your thoughts on Tauri. Electron comes with a RAM price. That is a well-known fact.
maybe Tauri can make this app feel even faster.
https://tauri.app/

I know what I do here is quite rude... maybe it is a big change and out of scope for what you can afford to spend on development. I'm writing this more out of curiosity about your thoughts than anything else.

**Comment by brigazvi** [comment]
oh, I just saw that you thinking of migrating to React. hell yeah. maybe I will even contribute. (also, dark mode is really a must-have)

**Comment by mignaway** [comment]
Hey, thanks for the compliment, I really appreciate it <3

Yes, at the moment I can't focus on this project, especially since I've just started designing and developing a version that I believe will be 20 times better than the current one, so I'm focused on that instead. Also, my design skills have improved significantly, so I think I can do much better in general. The new app will have many more features and will look even better.

Regarding Tauri, thanks for the advice, I could indeed use Tauri instead of Electron for this new project, thanks a lot!

**Comment by mignaway** [comment]
Anyone can contribute to the project btw, although it's quite difficult since I didn't manage the code very well hahaha

**Comment by brigazvi** [comment]
@mignaway I can't find the new project on your public repository. is it private?

**Comment by brigazvi** [comment]
glad to hear you put time and effort into this. good luck!
